name : My First workflow
on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls -la
      - name: Print Hello World
        run: echo "Hello World"