name: GH Actions - First Workflow - Demo 2
on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls -la
      - name: Print Hello World
        run: echo "Hello World"
      - name: Print Date and Time
        run: 'echo "Current date and time: $(date)"'
      - name: Print Hostname  
        run: 'echo "Current hostname: $(hostname)"'